Create schema.py
BloomTech-Labs/underdog-devs-ds-a pull request #111
Opened 2022-04-26 14:30 UTC by GermanParra

## Description

https://www.loom.com/share/d07a727e586f49e0b45f706b32ee21ec

Created schema.py file with pydantic schemas.

Note: The schemas include all the collected information from mentees and mentors but can be easily changed to omit unnecessary fields, after been implemented in the API endpoints.

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-26 14:44 UTC, BrokenShell requested changes
Great job over all. However, I think we need to make some changes based on our last conversation with Jason. Let's run through updates in Office Hours.

2022-04-27 02:57 UTC, mikayla-kosmala approved these changes
Glad to see that all the changes from the conversation with Jason we implemented! I do worry about the ones we took out, but that can be implemented later :)

2022-04-27 15:18 UTC, BrokenShell commented on app/schema.py
> +    teck_stacks = Literal[
`tech_stack` not `teck_stack`

2022-04-27 16:18 UTC, GermanParra commented on app/schema.py
> +    teck_stacks = Literal[
I just fixed, thank you.

2022-04-27 16:47 UTC, jinjahninjah requested changes
Don't forget to refactor any code that uses the tech_stack literal 👍

2022-04-27 17:43 UTC, GermanParra commented
> Don't forget to refactor any code that uses the tech_stack literal 👍
I just did thank you 👍

2022-04-27 17:56 UTC, jinjahninjah approved these changes

2022-04-27 18:13 UTC, derekjpeters commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test Card 1](https://trello.com/c/ppyR7Rpj/7-test-card-1)

2022-04-27 18:31 UTC, merged