Features/reseeding db
BloomTech-Labs/underdog-devs-ds-a pull request #113
Opened 2022-04-27 19:12 UTC by cbell98

## Description
https://www.loom.com/share/f53a65f0fc034414bf7ecae2154cf723 

Updated the Mentor and Mentee classes in the user_generators.py file to reflect the current schema.  Added 5 new data options to the data_options.py file to help generate new fields.  Preparing the MongoDB database to be reseeded. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-28 18:51 UTC, mikayla-kosmala commented on data_generators/data_options.py
> +states = (
data_option.py file looks good!

2022-04-28 18:54 UTC, mikayla-kosmala requested changes
Can you change the tech_stack, skill_level options to reflect what is currently on the Intake forms.
Also remove preferred_mentee_exp_level from the Mentor class. Other than that it looks pretty good!

2022-04-28 18:55 UTC, GermanParra approved these changes

2022-04-28 21:07 UTC, mikayla-kosmala approved these changes
Approved! Good Job!

2022-04-28 23:05 UTC, jinjahninjah approved these changes
:shipit:

2022-04-30 16:32 UTC, GermanParra requested changes
In the schema.py we should probably delete the following fields also.
- Mentor -> 'preferred_mentee_exp_level'
- MentorUpdate -> 'preferred_mentee_exp_level'  and 'profile_id'
- Mentee -> ' experience_level'
- MenteeUpdate ->  ' experience_level' and 'profile_id'

2022-04-30 16:40 UTC, mikayla-kosmala commented
I believe we still need mentee experience level. Not sure exactly what we will be doing with it, but we need it for now.

2022-05-02 15:39 UTC, GermanParra commented
> In the schema.py we should probably delete the following fields also.
> 
> * Mentor -> 'preferred_mentee_exp_level'
> * MentorUpdate -> 'preferred_mentee_exp_level'  and 'profile_id'
> * Mentee -> ' experience_level'
> * MenteeUpdate ->  ' experience_level' and 'profile_id'

Disregard the previous comment, another PR was created to work in this changes. Excellent work!

2022-05-02 15:40 UTC, GermanParra approved these changes

2022-05-02 15:43 UTC, mikayla-kosmala commented
> Let's remove the skill level field, as per our last talk with Jason.

Do we still want to remove them if we have a pull request working on this?
[#119](https://github.com/BloomTech-Labs/underdog-devs-ds-a/pull/119)

2022-05-02 16:01 UTC, BrokenShell approved these changes

2022-05-02 17:59 UTC, merged