Removed Tech Stack and Experience Variables
BloomTech-Labs/underdog-devs-ds-a pull request #119
Opened 2022-04-29 00:35 UTC by AdamHVu

## Description

This was a relatively simple change as it was warranted by Jason. There were variables in the schema that were not on the required list of important info because they were already handled previously and as such I had removed the tech_stack variable from both Mentor and Mentee and the experience levels of current mentees.

## Type of change
- [X] This change requires a documentation update

## Checklist:

- [X]  My code follows PEP8 style guide
- [X]  I have removed unnecessary print statements from my code
- [X]  I have made corresponding changes to the documentation if necessary
- [X]  My changes generate no errors
- [X] No commented-out code
- [X]  Size of pull request kept to a minimum
- [X]  Pull request description clearly describes changes made & motivations for said changes

My Loom Video: https://www.loom.com/share/9fddcf2e83ea4bcdbcd334a5500f8d73

2022-04-29 15:23 UTC, BrokenShell requested changes
The idea was to remove the specification of tech_stack to only allow these: ["Career Development", "Frontend", "Backend", "Design UI/UX", "iOS", "Android", "Data Science"]
We still want the field, just not the specific check.

2022-05-02 15:33 UTC, AdamHVu commented
> The idea was to remove the specification of tech_stack to only allow these: ["Career Development", "Frontend", "Backend", "Design UI/UX", "iOS", "Android", "Data Science"] We still want the field, just not the specific check.

Ah okay, a misunderstanding on my part. I have fixed it and pushed my changes!

2022-05-02 17:16 UTC, cbell98 approved these changes
Looks good - schema.py now lines up with user_generators.py file.

2022-05-02 18:06 UTC, BobbyWilt approved these changes

2022-05-02 18:17 UTC, VABIII approved these changes

2022-05-03 17:47 UTC, merged