Update mentee and mentor schema
BloomTech-Labs/underdog-devs-ds-a pull request #124
Opened 2022-05-05 16:53 UTC by BobbyWilt

## Description

Worked with Kevin to pair program updates to the mentee and mentor schemas.  The old schemas for both mentee and mentor had a field titled "looking_for" that had a selection for types of help either the mentee was interested in receiving or the mentor was hoping to provide.  This one field was separated into 3 separate fields for each option: job_help, industry_knowledge, and pair_programming.  The "looking_for" schema field was deleted and these 3 fields were added for the following schemas: Mentee, MenteeUpdate, Mentor, MentorUpdate.

[https://www.loom.com/share/59b868e8db324a1e881e1e253864cae1](Loom Video of Changes)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-05-05 17:08 UTC, mikayla-kosmala approved these changes
Nice Job!

2022-05-05 17:17 UTC, cbell98 approved these changes
Nice work continuing to keep schema.py inline with front-end updates. You might need to re-paste your Loom video link.

2022-05-05 18:02 UTC, amballa commented
Good job. I think this new schema makes more sense.

2022-05-05 18:04 UTC, amballa approved these changes
Good job. I think this new schema makes more sense.

2022-05-05 19:01 UTC, Lopez-John approved these changes
Great work updating the schema

2022-05-05 22:59 UTC, tammer81 approved these changes
Great first contribution! New schema much more intuitive

2022-05-05 23:01 UTC, Ike888 commented
This is a nice update to the schema, well-done. I had an issue with the loom video link, for some reason it didn't work for me!

2022-05-06 00:54 UTC, Ike888 approved these changes
Clean code! And this is a much-needed update to the schema.

2022-05-06 01:31 UTC, GermanParra approved these changes

2022-05-08 18:45 UTC, jinjahninjah requested changes
Nice work keeping the communication flowing between Web and DS! For lines 59 and 79, is this change for Web? The only changes I have are in the PR description:
- Remove the boilerplate code
- (Loom Video of Changes) should be at the beginning of your Loom link and it'll render

2022-05-09 22:01 UTC, BobbyWilt commented
> Nice work keeping the communication flowing between Web and DS! For lines 59 and 79, is this change for Web? The only changes I have are in the PR description:
> 
>     * Remove the boilerplate code
> 
>     * (Loom Video of Changes) should be at the beginning of your Loom link and it'll render



> Nice work keeping the communication flowing between Web and DS! For lines 59 and 79, is this change for Web? The only changes I have are in the PR description:
> 
>     * Remove the boilerplate code
> 
>     * (Loom Video of Changes) should be at the beginning of your Loom link and it'll render

Just removed the "Fixes (bug)" section on the pull request description and reformatted the loom link.

2022-05-09 22:05 UTC, jinjahninjah approved these changes

2022-05-13 00:49 UTC, ad-victoriam-101 approved these changes
Looks Good,

2022-05-16 19:16 UTC, merged