Documentation/adding ds and general documentation
BloomTech-Labs/underdog-devs-ds-a pull request #127
Opened 2022-05-05 20:22 UTC by mikayla-kosmala

## Description

Created a bunch of documentation for the next cohort to be able to read to be able to stay up to date with what is going on.

**App_folder_documenation**
- Contains some information about all the files living in the app folder documentation
### General documentation folder:
**Intake form documentation**
- This contains all google docs and dataflow charts about the intake form
- All the tickets that have been worked on to get the intake forms looking better

**DS api contract** 
- This contains our link to elasticbeanstalk since that is currently the source of truth for the DS API and needs to be communicated across all teams.

## Type of change

- [x] New documentation

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-05-05 20:24 UTC, tammer81 approved these changes
A much-needed resource; thank you for putting this together

2022-05-05 20:46 UTC, VABIII approved these changes
Excellent job untangling all that

2022-05-05 22:27 UTC, Lopez-John approved these changes
Great way to document what was done for the next cohort coming through. Amazing work.

2022-05-05 22:30 UTC, Ike888 commented
This is great; thank you for all your hard work!

2022-05-05 22:36 UTC, benedictSchurwanz commented
This is really so cool

2022-05-05 22:41 UTC, kevinbui100 approved these changes
I love what you've done here. You are a trailblazer!

2022-05-06 00:49 UTC, Ike888 approved these changes
Mikayla, you have done a fabulous job; future developers will thank you for this!

2022-05-06 00:50 UTC, Ike888 approved these changes
This is a great start to having all the documentation in just one place.

2022-05-06 01:43 UTC, GermanParra approved these changes
Awesome work! , well organized, clear, and objective. This document would help cohorts get familiar with the code base quickly.

2022-05-06 19:05 UTC, BobbyWilt approved these changes

2022-05-08 21:48 UTC, jinjahninjah requested changes
Just a couple of edits in the comments then it should be good to go 👍

2022-05-08 21:48 UTC, jinjahninjah commented on app/readme.md
> +Not 100% sure what this file contains, but it seems important to working mongodb
`data.py` is where the MongoDB interface (CRUD Operations) are housed.

2022-05-08 21:48 UTC, jinjahninjah commented on app/readme.md
> +
Lines 24-27 seem to be out of place-- I'm not sure what they are. Remove this as you call out more info in the doc strings.

2022-05-08 21:48 UTC, jinjahninjah commented on app/readme.md
> +This file current contains the function that is used in the /financial_aid/{profile_id} endpoint.
current -> currently

2022-05-09 15:44 UTC, jinjahninjah approved these changes

2022-05-09 17:59 UTC, merged