Feature/mentor model update
BloomTech-Labs/underdog-devs-ds-a pull request #158
Opened 2022-06-29 22:40 UTC by willisbridges

Co-authors: Jason Gersing, Cristian Ibarra-Villegas, Martha Gonzalez

Mentor collection update. Part of overarching plan to redo Database architecture to capture desired data with additional fields. For visibility, check this [excel spreadsheet](https://docs.google.com/spreadsheets/d/1dt54x0OVqgNfmGfW_omdQtEu6NXPfMZz_DUQKR7HCXo/edit?usp=sharing) (specifically the Refactor Final Draft tab) to see our high-level plans for refactoring each table.

Compiled new fields to Mentor class for architectural overhaul.

Please delete options that are not relevant.

- [X] New feature

- [X] My code follows PEP8 style guide
- [X] I have removed unnecessary print statements from my code
- [X] I have made corresponding changes to the documentation if necessary
- [X] My changes generate no errors
- [X] No commented-out code
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

2022-06-30 00:33 UTC, sayerjk commented on app/schema.py
> +    updated_ar: datetime
typo right ar `updated_ar`

2022-06-30 01:05 UTC, annakoduru6 submitted a review, later dismissed
Besides the typo Sayer pointed out (updated_at), looks good.

2022-06-30 02:45 UTC, marthabg commented on app/schema.py
> +    updated_ar: datetime
fixed

2022-06-30 06:41 UTC, sayerjk commented on app/schema.py
> +    is_active: bool
Have we discussed setting default values here?

2022-06-30 06:42 UTC, sayerjk commented on app/schema.py
Have we considered setting defaults for `is_active` and `accepting_new_mentees`?

2022-06-30 22:52 UTC, sspradling78 submitted a review, later dismissed
Looks good, I approve.

2022-06-30 23:32 UTC, zdravoj requested changes
validate_status in MentorUpdate collection needs to be a stringLiteral with the same list of string choices as in Mentor collection.

created_at should not exist as an updatable option in MentorUpdate collection. This field is set when the mentor is created and cannot be altered.

2022-06-30 23:32 UTC, zdravoj commented on app/schema.py
>      validate_status: Optional[constr(max_length=255)]
validate_status in MentorUpdate collection needs to be changed from a string to stringLiteral to reflect same changes in Mentor collection

2022-06-30 23:32 UTC, zdravoj commented on app/schema.py
> +    created_at: Optional[datetime]
created_at should not be an alterable field - it is set when the mentor is created. Please remove created_at from MentorUpdate collection.

2022-07-01 16:06 UTC, zdravoj approved these changes

2022-07-01 16:18 UTC, opeterschmidt approved these changes

2022-07-01 17:18 UTC, bummings commented
> This PR should be connected to BL-488; BL-490 doesn't seem to exist on Jira.
> 
> `MentorIntake` model should be removed. Now that `Mentor` is fully updated to match the new architecture, `MentorIntake` is obsolete and it's safe to remove it.

This is correct, we are working on [#448](https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/10?modal=detail&selectedIssue=BL-488&search=488)

2022-07-06 18:44 UTC, ad-victoriam-101 approved these changes
Looks good,

2022-07-11 16:20 UTC, jinjahninjah approved these changes
:shipit:

2022-07-12 16:55 UTC, rogerfvieira approved these changes
Great effort by all the teams on cleaning up the schema for database.

2022-07-13 22:44 UTC, merged