BL-781/mentor_mentee_update
BloomTech-Labs/underdog-devs-ds-a pull request #210
Opened 2022-08-09 19:23 UTC by jack-semder

## Description

We made changes to the schema file, specifically removing the profile_id attribute from MenteeUpdate and MentorUpdate.

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-08-09 22:02 UTC, zdravoj requested changes
The changes address the needs of the ticket. However, confirm with @paulstgermain that the PR for BL-684 is merged before this one, as the code from that PR is showing up here in the changed files.

2022-08-10 00:16 UTC, nathancai97 commented
Great job updating the schema, the schema validation testing are descriptive and easy to understand!

2022-08-10 00:17 UTC, nathancai97 submitted a review, later dismissed
Great job updating the schema, the schema validation testing are descriptive and easy to understand!

2022-08-10 16:28 UTC, jettyblue submitted a review, later dismissed
Nice work with the schema updates and test coverages, looks great!

2022-08-10 18:59 UTC, L0lbrich approved these changes
Good change! We definitely wouldn't want profile_id's being changed during this step

2022-08-10 20:12 UTC, BrokenShell requested changes

2022-08-10 20:12 UTC, BrokenShell commented on test_coverage/schema_validation_testing.py
> +    mentee = RandomMentee()
This file has old changes from another branch that has since been updated. This needs to be addressed before this branch gets merged.

2022-08-10 22:04 UTC, jettyblue approved these changes
Looks great!

2022-08-10 22:11 UTC, closed without merging