BL-877 DS Implement timestamping for create_many database method
BloomTech-Labs/underdog-devs-ds-a pull request #234
Opened 2022-08-26 00:10 UTC by stevenhastings

## Description
By adding the timestamp to the create_many method we're are removing the theoretical wall that was standing in the way between it and our randomizer's ability to do its job. This sequence of events was causing some turbulence for Front-End if they ever decided to do something CRAZY like request more than a single document in one call. Next, I was having difficulty making an errorless connection to our database and realized that MongoClient requires TLS certificate for secure communication sometimes python is unable to request via TLS so we explicitly mention for MongoClient to request to MongoDB using certifi package. Certifi has been added to requirements.txt. If anyone has any questions or concerns, feel free to reach out and I'll do my best to field them. Happy Coding!!!

## Jira Ticket
[The Sandman the KanBan and Me](https://bloomtechlabs.atlassian.net/browse/BL-877)

## Type of Change
- [x] Bug fix

## Checklist
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video

2022-08-26 02:58 UTC, BrokenShell requested changes
Good work, I have one very minor change for ya.

2022-08-26 02:58 UTC, BrokenShell commented on requirements.txt
> +
This is good work, let's get rid of that blank line (11) in the requirements.txt file.

2022-08-26 16:49 UTC, jack-semder submitted a review, later dismissed
Nice changes and a very detailed description of improvements, good work!

2022-08-26 18:38 UTC, stevenhastings reviewed
This resolved Roberts concern with the VOID! Also, the blank space in the requirements.txt file.

2022-08-26 19:19 UTC, BrokenShell approved these changes

2022-08-26 19:19 UTC, BrokenShell commented
This looks great, good job!

2022-08-29 16:06 UTC, jinjahninjah requested changes
Nice catch! Seemingly small, but fixes issues down the line.

2022-08-29 17:46 UTC, jinjahninjah approved these changes

2022-09-01 14:18 UTC, merged