BL-970-ds-i-want-to-see-my-mentees-mentors
BloomTech-Labs/underdog-devs-ds-a pull request #253
Opened 2022-10-11 21:59 UTC by JeffDesch

## Description
This feature branch implements the DS side of the "I want to see my mentees/mentors" User Story.
The API was updated with additional endpoints supporting the creation and deletion of mentor-mentee matches (stored in a new 'Matches' db collection) and retrieval of matching 'Mentee' or 'Mentor' records from a mentor/mentee query. Additionally, specialized query methods were added to the MongoDB class to support the operations of the endpoints.

## Jira Ticket
[BL-970](https://bloomtechlabs.atlassian.net/browse/BL-970)

## Type of Change
- [x] New feature

## Checklist
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video
TBA: Soon(TM)

2022-10-11 22:09 UTC, BrokenShell commented
This is a fantastic contribution to the project. Great work! I can't wait to see it in action.

2022-10-11 22:10 UTC, BrokenShell commented on app/routers/match_router.py
> +    @return JSON[Boolean] - success or failure of update</pre></code>"""
small type here (i think it should say `@return JSON[Boolean] - success or failure of delete</pre></code>` Be careful of the copy/pasta bug ;)

2022-10-11 22:11 UTC, BrokenShell commented on app/routers/match_router.py
> +    data = data.dict()
small type here (i think it should say @return JSON[Boolean] - success or failure of creation</pre></code> Be careful of the copy/pasta bug ;)

2022-10-11 22:14 UTC, BrokenShell commented on app/routers/match_router.py
> +        db_col = "Mentees"
is `db_col` actually being used?

2022-10-11 22:15 UTC, BrokenShell commented on app/routers/match_router.py
> +    query = query.dict()
you take the query from the input, but then later you overwrite it, not sure what was intended here.

2022-10-11 22:18 UTC, BrokenShell requested changes
This is a great start, I left a few notes - nothing major.

2022-10-12 12:44 UTC, nikolayglushetskiy approved these changes
Great job!

2022-10-13 15:23 UTC, zoebrantley approved these changes
Looks great!! Really excited to see this made.

2022-10-13 15:37 UTC, merged