Feature: Random mentor suggestions endpoint
BloomTech-Labs/underdog-devs-ds-a pull request #32
Opened 2022-02-11 20:23 UTC by ulloa

## Description

Added an endpoint for random mentor suggestions. This is so that we can start hooking up data between the web api and data science api.

[https://trello.com/c/h4lW4rIU](Trello Card 159)

https://www.loom.com/share/065e1fd52536410a97616eebddba6440

Please delete options that are not relevant.

- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-02-11 22:41 UTC, RylandGomez commented
Just a thought, perhaps it would be better to assign the mentors variable within the API route? This would avoid having to import the database within the ML interface and improve encapsulation, in my mind. I'd like to discuss if possible before further reviewing.

2022-02-11 22:49 UTC, ulloa commented
I'm making that change right now @RylandGomez

2022-02-11 23:03 UTC, RylandGomez requested changes
First off, thank you for adding __pycache__/ into the .gitignore file haha
Beyond that, the functionality for the code seems sound. My issue lies in the implementation. Specifically, the Matcher class currently seems to break encapsulation. I outlined my thoughts on how this could potentially be addressed with line comments.
If I'm wrong on any of this, feel free to call me out and discuss!

2022-02-11 23:22 UTC, ulloa commented on app/model.py
> +db = MongoDB("UnderdogDevs")
I think this one I fixed already, with exception to the when run as main.

2022-02-11 23:30 UTC, ulloa commented on app/api.py
> +    matcher = Matcher()
I'll look into this. Anyone else sure about it?

2022-02-11 23:41 UTC, ulloa commented on app/model.py
> +        mentors = db.read("Mentors", None)
With the db as an argument of the Matcher class now, can you look see if it should still be changed? 

If I go into the api.py, and change pass the following as an argument to `Matcher(API.db.dataframe('mentors'))` the `matcher.random_recommendations`, that could also work. 

Also, now I'm considering changing the name from random_recommendations to a verb.

2022-02-12 00:04 UTC, RylandGomez requested changes
Line comments go into detail, but tl;dr the assert in class Matcher doesn't seem appropriate, and encapsulation issue in model.py persists.

2022-02-12 00:16 UTC, RylandGomez commented on app/api.py
> +    matcher = Matcher()
iirc in office hours, Robert mentioned something about instantiating classes one level higher than where they are going to be used. My memory's a little foggy on the specifics, though, which is why I'm not so confident in raising this as an error.

2022-02-14 15:47 UTC, BrokenShell commented on app/api.py
> +    matcher = Matcher()
This is a great conversation! We'll definitely talk about this more in office hours.

2022-02-15 17:27 UTC, ulloa commented
I'm closing this for now. I believe #37 is the better direction for this.

2022-02-17 22:54 UTC, closed without merging