Update README
BloomTech-Labs/underdog-devs-ds-a pull request #36
Opened 2022-02-14 21:08 UTC by rodricobsanchez

Description

Update README

Type of change

This change requires a documentation update

Checklist:
 My code follows PEP8 style guide
 I have removed unnecessary print statements from my code
 I have made corresponding changes to the documentation if necessary
 My changes generate no errors
 No commented-out code
 Size of pull request kept to a minimum
 Pull request description clearly describes changes made & motivations for said changes

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows PEP8 style guide
- [ ] I have removed unnecessary print statements from my code
- [ ] I have made corresponding changes to the documentation if necessary
- [ ] My changes generate no errors
- [ ] No commented-out code
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-02-14 23:19 UTC, RylandGomez reviewed
Overall great changes and formatting, I just have the one gripe concerning upper management being cataloged in FT 42. I think listing them with their titles at the top of the list is more applicable, since their roles supersede any single team iteration.

2022-02-15 01:25 UTC, rodricobsanchez commented
> Overall great changes and formatting, I just have the one gripe concerning upper management being cataloged in FT 42. I think listing them with their titles at the top of the list is more applicable, since their roles supersede any single team iteration.

Please kindly check updated Contributors section I added your suggestion

2022-02-15 07:40 UTC, RylandGomez requested changes
Reformatting of Contributors looks fantastic! One last thing I did notice was that Key Features repeats its content three times. Fix that and it's an easy approval from me!

2022-02-15 07:40 UTC, RylandGomez commented on README.md
> +
Content repeated three times

2022-02-15 13:37 UTC, rodricobsanchez commented on README.md
> +
forgot that lol

2022-02-15 14:32 UTC, rodricobsanchez commented on README.md
> +
should be ready for review

2022-02-15 16:13 UTC, Annapurnaj91 approved these changes
Everything looks good for me

2022-02-15 16:52 UTC, RylandGomez approved these changes
Solid README that's expandable in future team iterations and project scope, with a clean layout. Nicely done!

2022-02-16 03:25 UTC, archana062031 approved these changes
Looks good to me!

2022-02-16 05:23 UTC, merged