create Collection Feedback and unique indexes for Collections
BloomTech-Labs/underdog-devs-ds-a pull request #40
Opened 2022-02-17 18:08 UTC by ChristineWangcy

## Description

• Data scientist needs mock data feedback from mentees to mentors to better predict the right mentors for mentees
• 5 categorical mock feedbacks are added in data_options.py: Poor, Fair, Good, Very Good, Excellent
• A new Collection Feedbacks is created in MongoDB Database UnderdogDevs 
• Unique indexes for Collections Mentees (user_id), Mentors (user_id), and Feedbacks (ticket_id) are set, to prevent inserting duplicate mock users or ticket_ids generated from user_generators.py (not from API) to MongoDB. This issue does not exist in API as API pops an error message when creating a duplicate user.

## Type of change

- [x] New feature

## Checklist:

- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-02-18 03:09 UTC, archana062031 requested changes
Plz add Classes and Functions Description or Docstring in the code for quicker understanding. Other than that everything looks great.

2022-02-18 15:52 UTC, Annapurnaj91 approved these changes
Nice approach to store the feedbacks in the MangoDb.

2022-02-18 16:06 UTC, archana062031 approved these changes
Looks good!

2022-02-18 16:12 UTC, sirivennelavempati approved these changes
Nice approach

2022-02-18 17:17 UTC, rodricobsanchez approved these changes
With the added docstring it is super clear what the class does! Superb job!

2022-02-18 18:00 UTC, mktran0417 approved these changes
Another thing that we could look into implementing is multiple reviews for different types of feedbacks like the stakeholder was suggesting. I.E. How did you feel about the session? How much did you feel you learned? Etc. Aside from that this looks really good!

2022-02-18 18:16 UTC, cainpalmer approved these changes
It is very easy to tell what you changed and the effort you put into making this a clean PR. Nice job

2022-02-18 18:49 UTC, LynnerKevin approved these changes
Looks like a good place to start

2022-02-18 19:54 UTC, tarasshulhan approved these changes

2022-02-18 20:27 UTC, bbellify approved these changes
Clear description of motivation and changes, look good 👍

2022-02-18 21:15 UTC, paulstgermain requested changes
This PR needs a Loom/video walkthrough of the changes made before I can merge it! 😱

2022-02-19 06:27 UTC, ChristineWangcy commented
> Another thing that we could look into implementing is multiple reviews for different types of feedbacks like the stakeholder was suggesting. I.E. How did you feel about the session? How much did you feel you learned? Etc. Aside from that this looks really good!

Good points! These may be congregated with Anna and Aarchana's paragraph feedback data, inserted into Feedbacks Collection to make diversity reviews. Needing Sentiment Analysis for the paragraph feedbacks first.

2022-02-19 06:28 UTC, ChristineWangcy commented
> This PR needs a Loom/video walkthrough of the changes made before I can merge it! 😱

Loom video added.

2022-02-21 03:57 UTC, paulstgermain approved these changes

2022-02-21 03:59 UTC, merged