Updated DS Mentor/Mentee schema to match backend
BloomTech-Labs/underdog-devs-ds-a pull request #62
Opened 2022-03-11 18:51 UTC by yefim-g

## Description

DS needs to match BE Mentor and Mentee creation to match their schema and store it.

## Type of change

- [X] New feature (updated)

## Checklist:

- [X] My code follows PEP8 style guide
- [X] I have removed unnecessary print statements from my code
- [X] I have made corresponding changes to the documentation if necessary
- [X] My changes generate no errors
- [X] No commented-out code
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

## Pair-Programming:
Who you paired with: Matt Grohnke
What pairing method(s) you used: Driver-navigator
How did it go? What did you learn?: The process went well, it sped up the time that it would have taken to make the updates.

Loom video: https://www.loom.com/share/0878bfa264174888b6b3aad964e5e909

2022-03-11 19:09 UTC, NPAPENBURG approved these changes
Good changes. Allows for our data to align with what is being sent from the backend.

2022-03-11 19:56 UTC, BrokenShell requested changes
see line 65 in the Mentee generator

2022-03-11 19:56 UTC, BrokenShell commented on data_generators/user_generators.py
> +        self.parole_restriction = ''
line 65: I found out this should be a random bool... we have a function for that:
```
self.parole_restriction = percent_true(50)
```

2022-03-11 20:18 UTC, NPAPENBURG approved these changes
Everything was cleaned up perfect.

2022-03-11 20:30 UTC, MichaelJP-DS approved these changes
Nice fix - Looks good to go!

2022-03-12 02:56 UTC, jonathan-mcgraw approved these changes
Looks great, sir. It will be nice to have databases across all 3 repos with matching schemas.

2022-03-14 20:07 UTC, jinjahninjah requested changes
Great job Yefim and Matt! The only changes I would suggest is keeping the doc string quotes to double quotes in the Mentor, Mentee, and Meeting classes, but other than that looks awesome!

2022-03-20 10:24 UTC, Zack-Quintana commented
Yeah, looks good. No fixes need to be implemented that I can think of. nice job

2022-03-22 19:37 UTC, jinjahninjah approved these changes

2022-03-22 20:20 UTC, BrokenShell approved these changes

2022-03-22 20:25 UTC, merged