Refactor/workshop
BloomTech-Labs/underdog-devs-ds-a pull request #83
Opened 2022-03-29 22:23 UTC by BrokenShell

# Refactor Workshop
Fixes several bugs and the code follows best practice a bit better (PEP8).

## Contributors
- jonathan mcgraw
- Yefim Gorodnitskiy
- Brogan Stich
- Eisenhower Lancheros
- John Baker
- Scott Reynders
- Nic Papenburg
- Elisa Mala

## PR Type
- [x] Bug fix

## Checklist:
- [x] My code follows PEP8 style guide
- [x] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-03-29 23:01 UTC, jinjahninjah requested changes
:shipit:

2022-03-29 23:01 UTC, jinjahninjah approved these changes

2022-03-29 23:43 UTC, yefim-g approved these changes
Definitely a beneficial workshop!

2022-03-30 00:37 UTC, BakerJr1904 commented on app/api.py
> +    }
I wish the f string worked; that would have been nice, to automate changes in the database with the docstring.

2022-03-30 00:38 UTC, BakerJr1904 approved these changes
It was a great time doing this PR

2022-03-30 01:22 UTC, Zack-Quintana approved these changes
Doesn't seem to be any changes needing to be made. Nice job

2022-03-30 02:19 UTC, hollberg approved these changes
Adding a 'neutral' option makes this feature much more useful.

2022-03-30 18:56 UTC, merged