Adding positive and negative extremes
BloomTech-Labs/underdog-devs-ds-a pull request #88
Opened 2022-03-31 23:06 UTC by Zack-Quintana

Description:
Added in a feature that returns all meetings with either an extremely positive or extremely negative sentiment score. extremely positive is defined as between 1 and 0.8 and extremely negative as -0.8 and -1

Co-authored by:
@Zack-Quintana
@BrandonSmith710
@hollberg

Type of change:
New feature

Checklist:
[x] My code follows PEP8 style guide
[x] I have removed unnecessary print statements from my code
[x] I have made corresponding changes to the documentation if necessary
[x] My changes generate no errors
[x] No commented-out code
[x] Size of pull request kept to a minimum
[x] Pull request description clearly describes changes made & motivations for said changes

2022-04-01 19:11 UTC, ZacharyRock approved these changes
In future iterations, could be improved with a wider example set so that what constitutes an extreme value could be more easily understood without manual experimentation, for example, to a stakeholder who might wonder what this feature determines as extreme.

2022-04-04 23:26 UTC, jinjahninjah approved these changes
Nice! This might be an area where you can experiment with the cutoffs. Also, give Altair a shot as a visualization library in your next iteration as it has some really cool functionality and gives the user the ability to interact with the visualizations.

2022-04-04 23:32 UTC, jinjahninjah requested changes
The only changes I would request is make sure your markdown is rendering in your PR's description, I would re-paste the [template](https://github.com/BloomTech-Labs/underdog-devs-ds-a/blob/main/pull_request_template.md) and remove the boilerplate code. Also, don't forget the Loom video.

2022-04-15 15:59 UTC, jinjahninjah approved these changes

2022-04-18 08:08 UTC, merged