Create topic_model.py
BloomTech-Labs/underdog-devs-ds-a pull request #91
Opened 2022-04-03 18:20 UTC by BrandonSmith710

Description: This file proposes a new method of topic modeling, called Non-Negative Matrix Factorization. The function, "topicizer" will accept a list of meeting notes, clean and vectorize the text, then return the desired number of topics; all from a minimally dependent environment.

Dependencies: sklearn.feature_extraction.text, sklearn.decomposition

Type of change:
- [ ] New feature
- [ ] This change requires a documentation update

Checklist:
- [ ] My code follows PEP8 style guide
- [ ] I have removed unnecessary print statements from my code
- [ ] I have made corresponding changes to the documentation if necessary
- [ ] My changes generate no errors
- [ ] No commented-out code
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-04-03 18:29 UTC, BrandonSmith710 commented
https://www.loom.com/share/b272dfd36f6e42e3ab271b67ea043d89

2022-04-04 23:11 UTC, hollberg approved these changes
Nice work! Adding the ability to classify text (such as meeting notes) by topic continues to build on the insights administrators will be able to extract from these artifacts.

2022-04-05 14:53 UTC, jinjahninjah requested changes
Great first attempt! There are a few things with PEP8 that need fixing like docstrings quotes and indentation should be 4 spaces not 2. You might want to look at your ```topicizer()``` method as it's currently throwing an error. Also, throw the sklearn library in the requirements.txt file 👍

2022-04-05 14:53 UTC, jinjahninjah commented on app/topic_model.py
> +  '''
PEP8 wants double quotes for docstrings

2022-04-05 17:00 UTC, BrandonSmith710 commented
> Great first attempt! There are a few things with PEP8 that need fixing like docstrings quotes and indentation should be 4 spaces not 2. You might want to look at your `topicizer()` method as it's currently throwing an error. Also, throw the sklearn library in the requirements.txt file 👍
Oops, thanks Royce! Will do.

2022-04-07 01:34 UTC, OlatomiAdigun approved these changes
Nice work. Good explanatory video

2022-04-19 02:23 UTC, closed without merging