Remove Numeric output from Sentiment endpoint
BloomTech-Labs/underdog-devs-ds-a pull request #98
Opened 2022-04-13 16:27 UTC by GermanParra

## Description
https://www.loom.com/share/243829d1f850495080bf0cb146562e0d

Eliminate the posibility for numerical output from the /sentiment end point in the API, making modifications on vader_sentiment and api scripts.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows PEP8 style guide
- [ ] I have removed unnecessary print statements from my code
- [x] I have made corresponding changes to the documentation if necessary
- [x] My changes generate no errors
- [x] No commented-out code
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-13 16:52 UTC, ad-victoriam-101 commented
This is not a bug this is a requested feature from [This ticket](https://trello.com/c/h5AS5v84/285-as-a-data-science-developer-i-want-the-option-to-classify-texts-sentiment-in-either-human-terms-ie-positive-or-negative-or-with)

This was done to allow the API to get the numeric for future NLTK processes.

2022-04-13 17:43 UTC, BrokenShell approved these changes
The change to the endpoint looks good too.

2022-04-13 17:43 UTC, BrokenShell commented on app/api.py
This looks fantastic! You made quick work of this task, way to go! If we need numeric output we can always create a second function for that.

2022-04-13 18:52 UTC, jinjahninjah requested changes
Looks great German! Thanks for cleaning up some old code, this is a very handy skill and practice makes perfect. 

The only changes to make are in the description of the PR. 
- Remove the boilerplate code: "Fixes # (issue)", "Delete options that are not relevant", and the like. 
- Since we are changing the API, go ahead and change the version number to 0.45.1 and we should be good to go. 

Other than the minor changes, great job on your first PR 👍

2022-04-14 18:43 UTC, mikayla-kosmala commented
Nice job on getting the first pull request done for the team!

2022-04-14 18:46 UTC, mikayla-kosmala approved these changes
Nice Job!

2022-04-14 18:48 UTC, merinakarki approved these changes

2022-04-14 19:22 UTC, jinjahninjah approved these changes

2022-04-15 20:07 UTC, merinakarki approved these changes

2022-04-15 20:07 UTC, merinakarki commented on app/api.py
> +    version="0.45.1",
Awesome work. You catched this and updated the version.

2022-04-18 08:12 UTC, merged

2022-05-17 21:18 UTC, kevinbui100 reviewed
The code looks fantastic!